package app.kuchupuchu.android

/**
 * Phone auth — the country-code side of the WhatsApp-style phone input.
 *
 * The user never types a country code: they pick a country (default
 * Bangladesh) and type only the national number, e.g. 1792929202. The app
 * builds the E.164 number itself, so the trunk zero is stripped here and the
 * worker's `normalizePhone()` (which accepts any +<8-15 digit> international
 * number and re-validates BD mobiles strictly) always receives a clean +
 * form. Both sides agree character-for-character, same contract as
 * PhoneVerifier.kt.
 */
data class KpCountry(val iso: String, val name: String, val dial: String)

/** The picker's default (owner rule: Bangladesh first). */
val DEFAULT_COUNTRY = KpCountry("BD", "Bangladesh", "880")

/** All ISO-3166 countries with their ITU dial codes, A→Z by name. */
val COUNTRIES: List<KpCountry> =
    listOf(
        KpCountry("AF", "Afghanistan", "93"),
        KpCountry("AL", "Albania", "355"),
        KpCountry("DZ", "Algeria", "213"),
        KpCountry("AD", "Andorra", "376"),
        KpCountry("AO", "Angola", "244"),
        KpCountry("AG", "Antigua & Barbuda", "1268"),
        KpCountry("AR", "Argentina", "54"),
        KpCountry("AM", "Armenia", "374"),
        KpCountry("AU", "Australia", "61"),
        KpCountry("AT", "Austria", "43"),
        KpCountry("AZ", "Azerbaijan", "994"),
        KpCountry("BS", "Bahamas", "1242"),
        KpCountry("BH", "Bahrain", "973"),
        KpCountry("BD", "Bangladesh", "880"),
        KpCountry("BB", "Barbados", "1246"),
        KpCountry("BY", "Belarus", "375"),
        KpCountry("BE", "Belgium", "32"),
        KpCountry("BZ", "Belize", "501"),
        KpCountry("BJ", "Benin", "229"),
        KpCountry("BT", "Bhutan", "975"),
        KpCountry("BO", "Bolivia", "591"),
        KpCountry("BA", "Bosnia & Herzegovina", "387"),
        KpCountry("BW", "Botswana", "267"),
        KpCountry("BR", "Brazil", "55"),
        KpCountry("BN", "Brunei", "673"),
        KpCountry("BG", "Bulgaria", "359"),
        KpCountry("BF", "Burkina Faso", "226"),
        KpCountry("BI", "Burundi", "257"),
        KpCountry("KH", "Cambodia", "855"),
        KpCountry("CM", "Cameroon", "237"),
        KpCountry("CA", "Canada", "1"),
        KpCountry("CV", "Cape Verde", "238"),
        KpCountry("CF", "Central African Republic", "236"),
        KpCountry("TD", "Chad", "235"),
        KpCountry("CL", "Chile", "56"),
        KpCountry("CN", "China", "86"),
        KpCountry("CO", "Colombia", "57"),
        KpCountry("KM", "Comoros", "269"),
        KpCountry("CG", "Congo - Brazzaville", "242"),
        KpCountry("CD", "Congo - Kinshasa", "243"),
        KpCountry("CR", "Costa Rica", "506"),
        KpCountry("HR", "Croatia", "385"),
        KpCountry("CU", "Cuba", "53"),
        KpCountry("CY", "Cyprus", "357"),
        KpCountry("CZ", "Czechia", "420"),
        KpCountry("DK", "Denmark", "45"),
        KpCountry("DJ", "Djibouti", "253"),
        KpCountry("DM", "Dominica", "1767"),
        KpCountry("DO", "Dominican Republic", "1809"),
        KpCountry("EC", "Ecuador", "593"),
        KpCountry("EG", "Egypt", "20"),
        KpCountry("SV", "El Salvador", "503"),
        KpCountry("GQ", "Equatorial Guinea", "240"),
        KpCountry("ER", "Eritrea", "291"),
        KpCountry("EE", "Estonia", "372"),
        KpCountry("SZ", "Eswatini", "268"),
        KpCountry("ET", "Ethiopia", "251"),
        KpCountry("FJ", "Fiji", "679"),
        KpCountry("FI", "Finland", "358"),
        KpCountry("FR", "France", "33"),
        KpCountry("GA", "Gabon", "241"),
        KpCountry("GM", "Gambia", "220"),
        KpCountry("GE", "Georgia", "995"),
        KpCountry("DE", "Germany", "49"),
        KpCountry("GH", "Ghana", "233"),
        KpCountry("GR", "Greece", "30"),
        KpCountry("GL", "Greenland", "299"),
        KpCountry("GD", "Grenada", "1473"),
        KpCountry("GT", "Guatemala", "502"),
        KpCountry("GN", "Guinea", "224"),
        KpCountry("GW", "Guinea-Bissau", "245"),
        KpCountry("GY", "Guyana", "592"),
        KpCountry("HT", "Haiti", "509"),
        KpCountry("HN", "Honduras", "504"),
        KpCountry("HK", "Hong Kong", "852"),
        KpCountry("HU", "Hungary", "36"),
        KpCountry("IS", "Iceland", "354"),
        KpCountry("IN", "India", "91"),
        KpCountry("ID", "Indonesia", "62"),
        KpCountry("IR", "Iran", "98"),
        KpCountry("IQ", "Iraq", "964"),
        KpCountry("IE", "Ireland", "353"),
        KpCountry("IL", "Israel", "972"),
        KpCountry("IT", "Italy", "39"),
        KpCountry("CI", "Ivory Coast", "225"),
        KpCountry("JM", "Jamaica", "1876"),
        KpCountry("JP", "Japan", "81"),
        KpCountry("JO", "Jordan", "962"),
        KpCountry("KZ", "Kazakhstan", "7"),
        KpCountry("KE", "Kenya", "254"),
        KpCountry("KI", "Kiribati", "686"),
        KpCountry("KW", "Kuwait", "965"),
        KpCountry("KG", "Kyrgyzstan", "996"),
        KpCountry("LA", "Laos", "856"),
        KpCountry("LV", "Latvia", "371"),
        KpCountry("LB", "Lebanon", "961"),
        KpCountry("LS", "Lesotho", "266"),
        KpCountry("LR", "Liberia", "231"),
        KpCountry("LY", "Libya", "218"),
        KpCountry("LI", "Liechtenstein", "423"),
        KpCountry("LT", "Lithuania", "370"),
        KpCountry("LU", "Luxembourg", "352"),
        KpCountry("MO", "Macau", "853"),
        KpCountry("MG", "Madagascar", "261"),
        KpCountry("MW", "Malawi", "265"),
        KpCountry("MY", "Malaysia", "60"),
        KpCountry("MV", "Maldives", "960"),
        KpCountry("ML", "Mali", "223"),
        KpCountry("MT", "Malta", "356"),
        KpCountry("MH", "Marshall Islands", "692"),
        KpCountry("MR", "Mauritania", "222"),
        KpCountry("MU", "Mauritius", "230"),
        KpCountry("MX", "Mexico", "52"),
        KpCountry("FM", "Micronesia", "691"),
        KpCountry("MD", "Moldova", "373"),
        KpCountry("MC", "Monaco", "377"),
        KpCountry("MN", "Mongolia", "976"),
        KpCountry("ME", "Montenegro", "382"),
        KpCountry("MA", "Morocco", "212"),
        KpCountry("MZ", "Mozambique", "258"),
        KpCountry("MM", "Myanmar", "95"),
        KpCountry("NA", "Namibia", "264"),
        KpCountry("NR", "Nauru", "674"),
        KpCountry("NP", "Nepal", "977"),
        KpCountry("NL", "Netherlands", "31"),
        KpCountry("NZ", "New Zealand", "64"),
        KpCountry("NI", "Nicaragua", "505"),
        KpCountry("NE", "Niger", "227"),
        KpCountry("NG", "Nigeria", "234"),
        KpCountry("KP", "North Korea", "850"),
        KpCountry("MK", "North Macedonia", "389"),
        KpCountry("NO", "Norway", "47"),
        KpCountry("OM", "Oman", "968"),
        KpCountry("PK", "Pakistan", "92"),
        KpCountry("PW", "Palau", "680"),
        KpCountry("PS", "Palestine", "970"),
        KpCountry("PA", "Panama", "507"),
        KpCountry("PG", "Papua New Guinea", "675"),
        KpCountry("PY", "Paraguay", "595"),
        KpCountry("PE", "Peru", "51"),
        KpCountry("PH", "Philippines", "63"),
        KpCountry("PL", "Poland", "48"),
        KpCountry("PT", "Portugal", "351"),
        KpCountry("QA", "Qatar", "974"),
        KpCountry("RO", "Romania", "40"),
        KpCountry("RU", "Russia", "7"),
        KpCountry("RW", "Rwanda", "250"),
        KpCountry("KN", "Saint Kitts & Nevis", "1869"),
        KpCountry("LC", "Saint Lucia", "1758"),
        KpCountry("VC", "Saint Vincent & Grenadines", "1784"),
        KpCountry("WS", "Samoa", "685"),
        KpCountry("SM", "San Marino", "378"),
        KpCountry("ST", "São Tomé & Príncipe", "239"),
        KpCountry("SA", "Saudi Arabia", "966"),
        KpCountry("SN", "Senegal", "221"),
        KpCountry("RS", "Serbia", "381"),
        KpCountry("SC", "Seychelles", "248"),
        KpCountry("SL", "Sierra Leone", "232"),
        KpCountry("SG", "Singapore", "65"),
        KpCountry("SK", "Slovakia", "421"),
        KpCountry("SI", "Slovenia", "386"),
        KpCountry("SB", "Solomon Islands", "677"),
        KpCountry("SO", "Somalia", "252"),
        KpCountry("ZA", "South Africa", "27"),
        KpCountry("KR", "South Korea", "82"),
        KpCountry("SS", "South Sudan", "211"),
        KpCountry("ES", "Spain", "34"),
        KpCountry("LK", "Sri Lanka", "94"),
        KpCountry("SD", "Sudan", "249"),
        KpCountry("SR", "Suriname", "597"),
        KpCountry("SE", "Sweden", "46"),
        KpCountry("CH", "Switzerland", "41"),
        KpCountry("SY", "Syria", "963"),
        KpCountry("TW", "Taiwan", "886"),
        KpCountry("TJ", "Tajikistan", "992"),
        KpCountry("TZ", "Tanzania", "255"),
        KpCountry("TH", "Thailand", "66"),
        KpCountry("TL", "Timor-Leste", "670"),
        KpCountry("TG", "Togo", "228"),
        KpCountry("TO", "Tonga", "676"),
        KpCountry("TT", "Trinidad & Tobago", "1868"),
        KpCountry("TN", "Tunisia", "216"),
        KpCountry("TR", "Türkiye", "90"),
        KpCountry("TM", "Turkmenistan", "993"),
        KpCountry("TV", "Tuvalu", "688"),
        KpCountry("UG", "Uganda", "256"),
        KpCountry("UA", "Ukraine", "380"),
        KpCountry("AE", "United Arab Emirates", "971"),
        KpCountry("GB", "United Kingdom", "44"),
        KpCountry("US", "United States", "1"),
        KpCountry("UY", "Uruguay", "598"),
        KpCountry("UZ", "Uzbekistan", "998"),
        KpCountry("VU", "Vanuatu", "678"),
        KpCountry("VA", "Vatican City", "379"),
        KpCountry("VE", "Venezuela", "58"),
        KpCountry("VN", "Vietnam", "84"),
        KpCountry("YE", "Yemen", "967"),
        KpCountry("ZM", "Zambia", "260"),
        KpCountry("ZW", "Zimbabwe", "263"),
    ).sortedBy { it.name }

/**
 * Builds the submittable E.164 number from the picked country and the typed
 * national digits: trunk zeros are stripped, the total must be 8–15 digits,
 * and a BD selection must still be a BD mobile (1[3-9]XXXXXXXX). Returns null
 * when the input is not usable — the caller shows the field error.
 */
fun buildE164(c: KpCountry, local: String): String? {
    val national = local.filter { it.isDigit() }.dropWhile { it == '0' }
    if (national.isEmpty()) return null
    val full = c.dial + national
    if (!Regex("^\\d{8,15}$").matches(full)) return null
    if (c.iso == "BD" && !Regex("^8801[3-9]\\d{8}$").matches(full)) return null
    return "+$full"
}
