package app.kuchupuchu.android

/**
 * Item 3 — GIF picker offline-first (100+ GIFs from Noto, style matches magnific animated emojis).
 *
 * - 100 GIFs bundled in assets/gifs/[codepoint].gif (512px, ~104M) — offline, no network.
 * - Source: https://fonts.gstatic.com/s/e/notoemoji/latest/{codepoint}/512.gif
 *   (same set as Noto animated emoji, which is what magnific's animated emojis showcase).
 * - Also have Lottie versions in assets/noto-emoji/ for smooth preview; GIF tab uses Lottie
 *   for grid preview (lighter) but assets/gifs/ are present for file-based send if needed.
 * - GifRepo lists codepoints + emoji chars for mapping.
 */

object GifRepo {
    data class GifItem(val codepoint: String, val emoji: String)

    val gifs: List<GifItem> = listOf(
        GifItem("1f31a", "🌚"),
        GifItem("1f31b", "🌛"),
        GifItem("1f31c", "🌜"),
        GifItem("1f31d", "🌝"),
        GifItem("1f31e", "🌞"),
        GifItem("1f31f", "🌟"),
        GifItem("1f389", "🎉"),
        GifItem("1f38a", "🎊"),
        GifItem("1f479", "👹"),
        GifItem("1f47b", "👻"),
        GifItem("1f47d", "👽"),
        GifItem("1f47e", "👾"),
        GifItem("1f47f", "👿"),
        GifItem("1f480", "💀"),
        GifItem("1f49b", "💛"),
        GifItem("1f4a5", "💥"),
        GifItem("1f4a9", "💩"),
        GifItem("1f4af", "💯"),
        GifItem("1f525", "🔥"),
        GifItem("1f573_fe0f", "🕳️"),
        GifItem("1f600", "😀"),
        GifItem("1f601", "😁"),
        GifItem("1f602", "😂"),
        GifItem("1f603", "😃"),
        GifItem("1f604", "😄"),
        GifItem("1f605", "😅"),
        GifItem("1f606", "😆"),
        GifItem("1f607", "😇"),
        GifItem("1f608", "😈"),
        GifItem("1f609", "😉"),
        GifItem("1f60a", "😊"),
        GifItem("1f60b", "😋"),
        GifItem("1f60c", "😌"),
        GifItem("1f60d", "😍"),
        GifItem("1f60e", "😎"),
        GifItem("1f60f", "😏"),
        GifItem("1f610", "😐"),
        GifItem("1f611", "😑"),
        GifItem("1f612", "😒"),
        GifItem("1f613", "😓"),
        GifItem("1f614", "😔"),
        GifItem("1f615", "😕"),
        GifItem("1f616", "😖"),
        GifItem("1f617", "😗"),
        GifItem("1f618", "😘"),
        GifItem("1f619", "😙"),
        GifItem("1f61a", "😚"),
        GifItem("1f61b", "😛"),
        GifItem("1f61c", "😜"),
        GifItem("1f61d", "😝"),
        GifItem("1f61e", "😞"),
        GifItem("1f61f", "😟"),
        GifItem("1f620", "😠"),
        GifItem("1f621", "😡"),
        GifItem("1f622", "😢"),
        GifItem("1f623", "😣"),
        GifItem("1f624", "😤"),
        GifItem("1f625", "😥"),
        GifItem("1f626", "😦"),
        GifItem("1f627", "😧"),
        GifItem("1f628", "😨"),
        GifItem("1f629", "😩"),
        GifItem("1f62a", "😪"),
        GifItem("1f62b", "😫"),
        GifItem("1f62c", "😬"),
        GifItem("1f62d", "😭"),
        GifItem("1f62e", "😮"),
        GifItem("1f62e_200d_1f4a8", "😮‍💨"),
        GifItem("1f62f", "😯"),
        GifItem("1f630", "😰"),
        GifItem("1f631", "😱"),
        GifItem("1f632", "😲"),
        GifItem("1f633", "😳"),
        GifItem("1f634", "😴"),
        GifItem("1f635", "😵"),
        GifItem("1f635_200d_1f4ab", "😵‍💫"),
        GifItem("1f636", "😶"),
        GifItem("1f636_200d_1f32b_fe0f", "😶‍🌫️"),
        GifItem("1f637", "😷"),
        GifItem("1f638", "😸"),
        GifItem("1f639", "😹"),
        GifItem("1f63a", "😺"),
        GifItem("1f63b", "😻"),
        GifItem("1f63c", "😼"),
        GifItem("1f63d", "😽"),
        GifItem("1f63e", "😾"),
        GifItem("1f63f", "😿"),
        GifItem("1f640", "🙀"),
        GifItem("1f641", "🙁"),
        GifItem("1f642", "🙂"),
        GifItem("1f642_200d_2194_fe0f", "🙂‍↔️"),
        GifItem("1f642_200d_2195_fe0f", "🙂‍↕️"),
        GifItem("1f643", "🙃"),
        GifItem("1f644", "🙄"),
        GifItem("1f648", "🙈"),
        GifItem("1f649", "🙉"),
        GifItem("1f64a", "🙊"),
        GifItem("1f910", "🤐"),
        GifItem("1f911", "🤑"),
        GifItem("1f912", "🤒"),
    )

    fun assetPath(codepoint: String): String = "gifs/$codepoint.gif"
    fun lottieAssetPath(codepoint: String): String = "noto-emoji/$codepoint.json"
}
